name: cds-lang-1
channels:
  - defaults
  - conda-forge
  - cogsci
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.3
  - confection=0.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.8.0
  - cupy=11.5.0
  - cymem=2.0.7
  - cython-blis=0.7.9
  - dataclasses=0.8
  - fastrlock=0.8
  - flake8=4.0.1
  - idna=3.3
  - importlib-metadata=2.0.0
  - intel-openmp=2022.1.0
  - jinja2=3.0.3
  - langcodes=3.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - markupsafe=2.1.2
  - mccabe=0.7.0
  - mkl=2022.1.0
  - murmurhash=1.0.9
  - mypy=0.910
  - mypy_extensions=0.4.4
  - numpy=1.24.2
  - openssl=3.0.8
  - packaging=21.3
  - pandas=1.5.3
  - pip=22.2.2
  - preshed=3.0.8
  - psutil=5.9.4
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydantic=1.10.5
  - pyflakes=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2021.3
  - requests=2.27.1
  - setuptools=65.5.0
  - shellingham=1.3.1
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.5.0
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.40.1
  - srsly=2.4.5
  - tbb=2021.7.0
  - thinc=8.1.7
  - tk=8.6.12
  - toml=0.10.2
  - tqdm=4.63.0
  - typer=0.4.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ucrt=10.0.20348.0
  - urllib3=1.26.8
  - vc=14.2
  - vs2015_runtime=14.34.31931
  - wasabi=1.1.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - zipp=3.7.0
  - zlib=1.2.13
  - pip:
      - colorama==0.4.6
      - en-core-web-lg==3.5.0
      - en-core-web-md==3.5.0
      - pathy==0.10.1
